language: cpp

os:
  - linux
  - osx

dist: trusty
sudo: false

# OS X only supports one image. Use the latest.
osx_image: xcode8.2

git:
  depth: 3

compiler:
  - clang
  - gcc

env:
  global:
    - BUILD_JOBS=2

  matrix:
    - BUILD_MODE="all"
    - BUILD_MODE="no-asm"
    - BUILD_MODE="asan"
    - BUILD_MODE="ubsan"
    - BUILD_MODE="codecov"

  exclude:
    # Skip GCC on OS X entirely
    - os: osx
      compiler: gcc

    # The sanitizer builds under Clang run slowly
    - compiler: clang
      env: BUILD_MODE="asan"
    - compiler: clang
      env: BUILD_MODE="ubsan"

script:
  - make "$BUILD_MODE" && ./cryptest.exe v && ./cryptest.exe tv all

after_success:
  - if [[ ( ("$BUILD_MODE" = "coverage") && ("$CC" = "gcc") ) ]]; then bash <(curl -s https://codecov.io/bash) fi;

# whitelist branches to avoid testing feature branches twice
branches:
  only:
    - master

addons:
  sonarqube: true

  coverity_scan:
    project:
      name: "cryptopp"
    build_command: "make -j 2"

#notifications:
#  email: jdoe@example.com
